Repository jasonwynn10/MyPlot, pull requests merged in 2020-10, with the labels that each got.

#344 Allow plots to have separate prices from eachother for claiming
  plugin.yml
  src/MyPlot/EventListener.php
  src/MyPlot/Plot.php
  src/MyPlot/forms/subforms/ClaimForm.php
  src/MyPlot/provider/JSONDataProvider.php
  src/MyPlot/provider/MySQLProvider.php
  src/MyPlot/provider/SQLiteDataProvider.php
  src/MyPlot/provider/YAMLDataProvider.php
  src/MyPlot/subcommand/ClaimSubCommand.php
Labels: BC-Breaks, PR: Feature Additions, Priority: Low, Status: Work In Progress

#343 Add Plot buy/selling
  plugin.yml
  resources/deu.ini
  resources/eng.ini
  resources/langtemplate.ini
  src/MyPlot/Commands.php
  src/MyPlot/EventListener.php
  src/MyPlot/MyPlot.php
  src/MyPlot/provider/SQLiteDataProvider.php
  src/MyPlot/subcommand/BuySubCommand.php
  src/MyPlot/subcommand/SellSubCommand.php
Labels: PR: Feature Additions, PR: Translation, Priority: Low, Status: Work In Progress

#337 Added forms
  resources/deu.ini
Labels: PR: Translation, Priority: Low, Resolution: Done
